const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY_NOTIFICATION_DRAWER';
const HIDE_NOTIFICATION_DRAWER = 'HIDE_NOTIFICATION_DRAWER';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
